{
 "title": "s3 bucket exporter",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "s3 status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(s3_endpoint_up) by(__name__)"
    }
   ]
  },
  {
   "title": "S3 total object number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(s3_total_object_number) by(__name__)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 total usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(s3_total_size) by(__name__)"
    }
   ]
  },
  {
   "title": "S3 usage by StorageClass",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(s3_total_size) by(storageClass)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 object number by StorageClass",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(s3_total_object_number) by(storageClass)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 total usage per bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (bucketName) (s3_bucket_size{})",
     "legendFormat": "{{ bucketName }}"
    }
   ]
  },
  {
   "title": "S3 usage by StorageClass per bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (bucketName, storageClass) (s3_bucket_size{})",
     "legendFormat": "{{ bucketName }} / {{ storageClass }}"
    }
   ]
  },
  {
   "title": "S3 total object number per bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucketName) (s3_bucket_object_number{})",
     "legendFormat": "{{ bucketName }}"
    }
   ]
  },
  {
   "title": "S3 object number by StorageClass per bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucketName, storageClass) (s3_bucket_object_number{})",
     "legendFormat": "{{ bucketName }} / {{ storageClass }}"
    }
   ]
  }
 ]
}