version: "3.5"
services:
  s3bucketexporter:
    image: docker.io/tropnikovvl/s3bucket_exporter:1.0.0
    restart: always
    ports:
      - "9655:9655"
    environment:
      S3_ENDPOINT: https://s3.us-east-1.amazonaws.com
      LISTEN_PORT: ":9655"
      S3_ACCESS_KEY: ABCD12345678
      S3_SECRET_KEY: mySecretKey
      S3_BUCKET_NAME: my-bucket-name
      S3_REGION: us-east-1
      S3_DISABLE_SSL: "False"
      S3_DISABLE_ENDPOINT_HOST_PREFIX: "False"
      S3_FORCE_PATH_STYLE: "False"
      LOG_LEVEL: Info
    healthcheck:
      test: curl -s -f http://localhost:9655/health
      timeout: 30s
      interval: 2m
      retries: 3
      start_period: 30s
