{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-bucket-exporter.fullname" . }}-secret-env
  labels:
    {{- include "s3-bucket-exporter.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
    {{- if typeOf $v | eq "string" }}
      {{- print (tpl $k $) ": " (tpl $v $ | b64enc) | nindent 2 }}
    {{- else }}
      {{- print (tpl $k $) ": " ($v | b64enc) | nindent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
