{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "s3-bucket-exporter.fullname" . }}
  labels:
    {{- include "s3-bucket-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout}}
  selector:
    matchLabels:
      {{- include "s3-bucket-exporter.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
