name: go-sec

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: go-sec-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Go-Sec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v7
      
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.29.0
        with:
          args: -exclude-dir=\.*test\.* ./...
          # args: -exclude=G204,G301,G302,G304,G306 -exclude-dir=\.*test\.* ./...
          # args: -no-fail -exclude-dir=\.*test\.* --verbose sonar -out=./gosec-report.json ./...
