name: static-check

on:
  push:
    branches:
      - master
      - develop
      - "dependabot/*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Static-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5

      - name: Generate mocks
        run: go generate ./...

      - name: Static Code Analysis
        uses: golangci/golangci-lint-action@v3
        with:
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
          args: |
            --timeout 5m --out-${NO_FUTURE}format checkstyle:golangci-report.xml --issues-exit-code 0 --enable errcheck,gosimple,govet,ineffassign,staticcheck,typecheck,unused,gocritic,asasalint,asciicheck,errchkjson,exportloopref,forcetypeassert,makezero,nilerr,unparam,unconvert,wastedassign,usestdlibvars 
          # --timeout 5m --out-format checkstyle:golangci-report.xml -issues-exit-code 0 

      - name: Cache golangci-lint report
        uses: actions/cache@v3
        id: restore-golangci-lint-report
        with:
          path: ./golangci-report.xml
          key: ${{ github.sha }}
